name: CI - CRUD Empleados

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Clonar repositorio
      uses: actions/checkout@v3

    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Instalar dependencias
      run: |
        pip install -r requirements.txt

    - name: Ejecutar pruebas
      run: |
        echo "No hay pruebas aún, pero el pipeline funciona"

    - name: Comprimir proyecto
      run: |
        zip -r crud_empleados_build.zip . -x "*.git*" "*.venv*" "__pycache__/*"

    - name: Subir artefacto ZIP
      uses: actions/upload-artifact@v4
      with:
        name: crud_empleados_build.zip
        path: crud_empleados_build.zip

